services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cmt
      POSTGRES_USER: cmt
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env.prod}
      # Para que psql no pida password en el healthcheck
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      # Ejecuta un SELECT 1 autenticado (más fiable que pg_isready sin usuario)
      test: ["CMD-SHELL", "psql -U cmt -d cmt -h 127.0.0.1 -p 5432 -c 'SELECT 1' >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    build: ./app/backend
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
      --proxy-headers --forwarded-allow-ips="*"
    environment:
      DATABASE_URL: postgresql+psycopg2://cmt:${POSTGRES_PASSWORD}@db:5432/cmt
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      FORWARDED_ALLOW_IPS: "*"
    env_file:
      - ./.env.prod
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; url='http://127.0.0.1:8000/healthz'; sys.exit(0 if getattr(urllib.request.urlopen(url, timeout=5),'status',200)==200 else 1)\""]
      interval: 30s
      timeout: 5s
      retries: 5

  worker:
    build: ./app/backend
    command: >
      celery -A core.celery_worker.celery_app worker
      -c ${CELERY_CONCURRENCY:-8}
      --prefetch-multiplier=${CELERY_PREFETCH:-1}
      -Ofair
      --loglevel=${CELERY_LOGLEVEL:-info}
    environment:
      PYTHONPATH: /app
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DATABASE_URL: postgresql+psycopg2://cmt:${POSTGRES_PASSWORD}@db:5432/cmt
      REDIS_URL: redis://redis:6379/0
    env_file:
      - ./.env.prod
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import os,sys,urllib.request,redis; urllib.request.urlopen('http://backend:8000/healthz',timeout=5); redis.from_url(os.environ['CELERY_BROKER_URL']).ping(); sys.exit(0)\""]
      interval: 30s
      timeout: 10s
      retries: 5

  beat:
    build: ./app/backend
    command: >
      celery -A core.celery_worker.celery_app beat
      --loglevel=info
    environment:
      PYTHONPATH: /app
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DATABASE_URL: postgresql+psycopg2://cmt:${POSTGRES_PASSWORD}@db:5432/cmt
      REDIS_URL: redis://redis:6379/0
    env_file:
      - ./.env.prod
    depends_on:
      worker:
        condition: service_started
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import os,sys,urllib.request,redis; urllib.request.urlopen('http://backend:8000/healthz',timeout=5); redis.from_url(os.environ['CELERY_BROKER_URL']).ping(); sys.exit(0)\""]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:alpine
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "443:443"
      # - "80:80"
    volumes:
      # Asegúrate de construir el frontend antes: npm ci && npm run build en ./app/frontend
      - ./app/frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  db-data: